apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-tutorial
  labels:
    app: flask-tutorial
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-tutorial
  template:
    metadata:
      labels:
        app: flask-tutorial
    spec:
      containers:
      - name: flask-tutorial
        image: flask-tutorial:latest
        ports:
        - containerPort: 80