apiVersion: v1
kind: Service
metadata:
  name: flask-tutorial
  namespace: default
spec:
  type: NodePort
  ports:
  - name: flask-tutorial
    port: 8008
    targetPort: http
  selector:
    app: flask-tutorial